#!/bin/bash

set -euo pipefail

mountargs=""
for arg in "$@"; do
	if [[ $arg != -* ]]; then
		mount="$(realpath $(dirname ${arg}))"
		if [[ -d "${mount}" ]]; then
			mountargs="${mountargs} -v${mount}:${mount}"
		fi
	fi
done

docker run \
	-v$(pwd):$(pwd) \
	-w$(pwd) \
	-v/var/run/libvirt:/var/run/libvirt \
	${mountargs} \
	--privileged \
	--network host \
	-it beshleman/runvm boot \
	$@
